### ISSUE TITLE
Need another maintainer?

### ISSUE THREAD

**Issue by MuellerSeb** [conda-forge/f90nml-feedstock#16]
Do you need help with maintaining this @cpelley? I am willing to help.

Cheers,
Sebastian

**Comment by cpelley** [comment]
Hi @MuellerSeb, more than happy for an extra pair of hands, appreciated :)

**Comment by MuellerSeb** [comment]
Will come up with a pull request then.. or you add me in one of the open pull requests. ;-)

**Comment by MuellerSeb** [comment]
Thanks!
